version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: d20_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:             # Load variables from .env
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
